server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/frequentmatchups
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
